<div class="section">
    <div class="container">
        <div class="content-section">
            <div class="title">
                <h1>Reservation (click your Table)</h1>
                <hr>
            </div>
        </div>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="img\reservation.jpg" usemap="#image-map">

        <map name="image-map">
            <area target="_self" alt="1" title="1" href="" coords="197,39,264,130" shape="rect">
            <area target="" alt="2" title="2" href="" coords="311,41,378,130" shape="rect">
            <area target="" alt="3" title="3" href="" coords="438,50,480,91" shape="rect">
            <area target="" alt="4" title="4" href="" coords="522,50,564,89" shape="rect">
            <area target="" alt="5" title="5" href="" coords="600,51,644,90" shape="rect">
            <area target="" alt="6" title="6" href="" coords="601,209,656,257" shape="rect">
            <area target="" alt="7" title="7" href="" coords="516,208,567,254" shape="rect">
            <area target="" alt="8" title="8" href="" coords="433,208,485,254" shape="rect">
            <area target="" alt="9" title="9" href="" coords="352,250,403,297" shape="rect">
            <area target="" alt="10" title="10" href="" coords="290,249,340,298" shape="rect">
            <area target="" alt="11" title="11" href="" coords="224,248,271,294" shape="rect">
            <area target="" alt="12" title="12" href="" coords="173,254,208,288" shape="rect">
            <area target="" alt="13" title="13" href="" coords="433,289,484,338" shape="rect">
            <area target="" alt="14" title="14" href="" coords="569,338,515,291" shape="rect">
            <area target="" alt="15" title="15" href="" coords="601,290,652,335" shape="rect">
            <area target="" alt="16" title="16" href="" coords="675,467,728,515" shape="rect">
            <area target="" alt="17" title="17" href="" coords="591,467,639,512" shape="rect">
            <area target="" alt="18" title="18" href="" coords="515,467,568,514" shape="rect">
            <area target="" alt="19" title="19" href="" coords="438,468,486,514" shape="rect">
            <area target="" alt="20" title="20" href="" coords="355,468,407,512" shape="rect">
            <area target="" alt="21" title="21" href="" coords="254,450,321,515" shape="rect">
            <area target="" alt="22" title="22" href="" coords="153,451,219,513" shape="rect">
            <area target="" alt="t1" title="t1" href="" coords="778,39,820,140" shape="rect">
            <area target="" alt="t2" title="t2" href="" coords="842,40,881,77" shape="rect">
            <area target="" alt="t3" title="t3" href="" coords="841,102,880,138" shape="rect">
            <area target="" alt="t4" title="t4" href="" coords="782,358,824,398" shape="rect">
            <area target="" alt="t5" title="t5" href="" coords="785,425,826,464" shape="rect">
            <area target="" alt="t6" title="t6" href="" coords="843,362,880,394" shape="rect">
            <area target="" alt="t7" title="t7" href="" coords="841,426,880,463" shape="rect">
            <area target="" alt="t8" title="t8" href="" coords="781,483,881,510" shape="rect">
            <area target="" alt="Bar" title="Bar" href="" coords="24,198,132,526" shape="rect">
        </map>
    </div>
</div>