-- MySQL Script generated by MySQL Workbench
-- Fri Jul 16 22:58:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GeorgeMboUtrecht
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GeorgeMboUtrecht` ;

-- -----------------------------------------------------
-- Schema GeorgeMboUtrecht
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GeorgeMboUtrecht` DEFAULT CHARACTER SET utf8 ;
USE `GeorgeMboUtrecht` ;

-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Rol` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Rol` (
  `rol` VARCHAR(25) NOT NULL,
  `omschrijving` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Password` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Password` (
  `email` VARCHAR(100) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Klant` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Klant` (
  `id` INT UNSIGNED NOT NULL DEFAULT 100000,
  `achternaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(10) NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mobiel` VARCHAR(10) NOT NULL,
  `rol` VARCHAR(25) NOT NULL DEFAULT 'klant',
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  `emailVerified` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Klant_Rol_idx` (`rol` ASC),
  CONSTRAINT `fk_Klant_Rol`
    FOREIGN KEY (`rol`)
    REFERENCES `GeorgeMboUtrecht`.`Rol` (`rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Klant_Password`
    FOREIGN KEY (`email`)
    REFERENCES `GeorgeMboUtrecht`.`Password` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Medewerker` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Medewerker` (
  `email` VARCHAR(100) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(10) NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `mobiel` VARCHAR(10) NOT NULL,
  `afkorting` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `afkorting_UNIQUE` (`afkorting` ASC),
  CONSTRAINT `fk_Medeqwerker_Password`
    FOREIGN KEY (`email`)
    REFERENCES `GeorgeMboUtrecht`.`Password` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Lespakket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Lespakket` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Lespakket` (
  `lespakket` VARCHAR(10) NOT NULL,
  `omschrijving` VARCHAR(100) NOT NULL,
  `aantalLessenKok` INT NOT NULL,
  `aantalLessenBarman` INT NOT NULL,
  `aantalLessenOber` INT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`lespakket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Student` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Student` (
  `studentnr` INT NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(25) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `mobiel` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `woonplaats` VARCHAR(45) NOT NULL,
  `straat` VARCHAR(60) NOT NULL,
  `postcode` VARCHAR(7) NOT NULL,
  `rol` VARCHAR(25) NOT NULL DEFAULT 'student',
  `docent` VARCHAR(5) NOT NULL,
  `lespakket` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`studentnr`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Student_Rol_idx` (`rol` ASC),
  INDEX `fk_Student_Docent_idx` (`docent` ASC),
  INDEX `fk_Student_LesPakket_idx` (`lespakket` ASC),
  CONSTRAINT `fk_Student_Rol`
    FOREIGN KEY (`rol`)
    REFERENCES `GeorgeMboUtrecht`.`Rol` (`rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Student_Password`
    FOREIGN KEY (`email`)
    REFERENCES `GeorgeMboUtrecht`.`Password` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Student_Docent`
    FOREIGN KEY (`docent`)
    REFERENCES `GeorgeMboUtrecht`.`Medewerker` (`afkorting`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Student_LesPakket`
    FOREIGN KEY (`lespakket`)
    REFERENCES `GeorgeMboUtrecht`.`Lespakket` (`lespakket`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`MedewerkerRol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`MedewerkerRol` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`MedewerkerRol` (
  `rol` VARCHAR(25) NOT NULL,
  `medewerker` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`rol`, `medewerker`),
  INDEX `fk_MedewerkerRol_Med_idx` (`medewerker` ASC),
  CONSTRAINT `fk_MedewerkerRol_Rol`
    FOREIGN KEY (`rol`)
    REFERENCES `GeorgeMboUtrecht`.`Rol` (`rol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_MedewerkerRol_Med`
    FOREIGN KEY (`medewerker`)
    REFERENCES `GeorgeMboUtrecht`.`Medewerker` (`email`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Werkdag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Werkdag` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Werkdag` (
  `datum` DATE NOT NULL,
  `weeknummer` INT NOT NULL,
  `jaar` INT NOT NULL,
  `dag` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`datum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Beroep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Beroep` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Beroep` (
  `beroep` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`beroep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`RestaurantInschrijving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`RestaurantInschrijving` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`RestaurantInschrijving` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `werkDatum` DATE NOT NULL,
  `student` INT NOT NULL,
  `beroep` VARCHAR(10) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_RI_Student_idx` (`student` ASC),
  INDEX `fk_RI_Beroep_idx` (`beroep` ASC),
  INDEX `fk_RI_Werdag_idx` (`werkDatum` ASC),
  CONSTRAINT `fk_RI_Student`
    FOREIGN KEY (`student`)
    REFERENCES `GeorgeMboUtrecht`.`Student` (`studentnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RI_Beroep`
    FOREIGN KEY (`beroep`)
    REFERENCES `GeorgeMboUtrecht`.`Beroep` (`beroep`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RI_Werdag`
    FOREIGN KEY (`werkDatum`)
    REFERENCES `GeorgeMboUtrecht`.`Werkdag` (`datum`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Beoordeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Beoordeling` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Beoordeling` (
  `id` INT NOT NULL,
  `inschrijving` INT NOT NULL,
  `oordeel` VARCHAR(500) NOT NULL,
  `voldoende` TINYINT NOT NULL DEFAULT 0,
  `begeleider` VARCHAR(5) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_Beorrdeling_RI_idx` (`inschrijving` ASC),
  INDEX `fk_Beoordeling_Medewerker_idx` (`begeleider` ASC),
  CONSTRAINT `fk_Beoordeling_RI`
    FOREIGN KEY (`inschrijving`)
    REFERENCES `GeorgeMboUtrecht`.`RestaurantInschrijving` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Beoordeling_Medewerker`
    FOREIGN KEY (`begeleider`)
    REFERENCES `GeorgeMboUtrecht`.`Medewerker` (`afkorting`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`BegeleidersRooster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`BegeleidersRooster` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`BegeleidersRooster` (
  `id` INT NOT NULL,
  `begeleider` VARCHAR(5) NOT NULL,
  `werkDatum` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BR_Werkdag_idx` (`werkDatum` ASC),
  INDEX `fk_BR_Begeleider_idx` (`begeleider` ASC),
  CONSTRAINT `fk_BR_Werkdag`
    FOREIGN KEY (`werkDatum`)
    REFERENCES `GeorgeMboUtrecht`.`Werkdag` (`datum`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_BR_Begeleider`
    FOREIGN KEY (`begeleider`)
    REFERENCES `GeorgeMboUtrecht`.`Medewerker` (`afkorting`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Review` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Review` (
  `id` INT NOT NULL DEFAULT 1000,
  `klant` VARCHAR(100) NOT NULL,
  `werkdag` DATE NOT NULL,
  `beoordeling` VARCHAR(255) NOT NULL,
  `sterren` INT NOT NULL DEFAULT 3,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `reactie` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_Review_Klant_idx` (`klant` ASC),
  INDEX `fk_Review_Werkdag_idx` (`werkdag` ASC),
  CONSTRAINT `fk_Review_Klant`
    FOREIGN KEY (`klant`)
    REFERENCES `GeorgeMboUtrecht`.`Klant` (`email`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Review_Werkdag`
    FOREIGN KEY (`werkdag`)
    REFERENCES `GeorgeMboUtrecht`.`Werkdag` (`datum`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Reactie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Reactie` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Reactie` (
  `id` INT NOT NULL,
  `review` INT NOT NULL,
  `reactie` VARCHAR(500) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_Reactie_Review_idx` (`review` ASC),
  CONSTRAINT `fk_Reactie_Review`
    FOREIGN KEY (`review`)
    REFERENCES `GeorgeMboUtrecht`.`Review` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeorgeMboUtrecht`.`Mededeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeorgeMboUtrecht`.`Mededeling` ;

CREATE TABLE IF NOT EXISTS `GeorgeMboUtrecht`.`Mededeling` (
  `id` INT NOT NULL,
  `mededeling` VARCHAR(500) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `GeorgeMboUtrecht`.`Rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `GeorgeMboUtrecht`;
INSERT INTO `GeorgeMboUtrecht`.`Rol` (`rol`, `omschrijving`) VALUES ('klant', 'bezoekers van het restaurant');

INSERT INTO `GeorgeMboUtrecht`.`Rol` (`rol`, `omschrijving`) VALUES ('student', 'studenten van MBO Utrecht');
INSERT INTO `GeorgeMboUtrecht`.`Rol` (`rol`, `omschrijving`) VALUES ('begeleider', 'begeleider van de studenten in dienst bij George');
INSERT INTO `GeorgeMboUtrecht`.`Rol` (`rol`, `omschrijving`) VALUES ('docent', 'schoolbegeleider');
INSERT INTO `GeorgeMboUtrecht`.`Rol` (`rol`, `omschrijving`) VALUES ('eigenaar', 'eigenaar van George');

COMMIT;

drop user if exists 'GeorgeUser'@'%';
drop user if exists 'GeorgeUser'@'localhost';

create user 'GeorgeUser'@'localhost' identified by 'George123';
grant all privileges on *.* to 'GeorgeUser'@'localhost';
flush privileges;

create user 'GeorgeUser'@'%' identified by 'George123';
grant all privileges on *.* to 'GeorgeUser'@'%' ;
flush privileges;


 
